# Generated by Django 5.1.3 on 2024-11-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_physician_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Physician',
        ),
        migrations.AlterModelOptions(
            name='physician',
            options={'ordering': ['name'], 'verbose_name_plural': 'Physicians'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.TextField(verbose_name='M/F'),
        ),
    ]
